development:
  adapter: sqlite3
  database: db/post-box-development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/post-box-test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/post-box-production.sqlite3
  pool: 5
  timeout: 5000
